### PR TITLE
Backport 25345 to make more tests pass

### PR DESCRIPTION
**Pull request by saraedum**
this does not really change anything but just adapt some doctests so we effectively skip them.

### CODE REVIEW

**Comment by isuruf** [comment]
This wouldn't help the testing setup that we have, since we are using a git checkout for running the doctests.

**Comment by saraedum** [comment]
I see. I'll see if I can change that easily. It's not so important of course.

**Comment by saraedum** [comment]
Hm...I meant to try to change our tests. Why did you close this so quickly?

**Comment by isuruf** [comment]
Oh, okay.

**Pull request merged**
