### PR TITLE
Backport #26451

### PR DESCRIPTION
**Pull request by saraedum**
to support newer versions of Sphinx

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin please rerender

**Comment by saraedum** [comment]
This needs https://github.com/conda-forge/iml-feedstock/pull/4.

**Comment by isuruf** [comment]
Lots of dependencies have to be rebuilt with new openblas version which would take some time. You can remove the last commit if you want this PR to be merged soon

**Comment by saraedum** [comment]
Yes, that's probably a good idea.

**Pull request merged**
