### PR TITLE
Enable sage -tp

### PR DESCRIPTION
**Pull request by saraedum**
we'll just fake that no packages are present until
https://trac.sagemath.org/ticket/20382 has been merged.

Note that we can not just override SAGE_SPKG_INST because sage-env
unfortunately overrides this variable again.

It's nice to be able to run `sage -tp` to get an idea of how much of the doctests we would pass at the moment.

### CODE REVIEW

**Comment by saraedum** [comment]
At the moment this fails with:
```
[151/468] gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -w -m64 -I/feedstock_root/build_artefacts/sagelib_1525107768700/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include -fPIC -I/feedstock_root/build_artefacts/sagelib_1525107768700/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include -I/feedstock_root/build_artefacts/sagelib_1525107768700/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include/python2.7 -I/feedstock_root/build_artefacts/sagelib_1525107768700/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python2.7/site-packages/numpy/core/include -I/feedstock_root/build_artefacts/sagelib_1525107768700/work/sage-8.1/src -I/feedstock_root/build_artefacts/sagelib_1525107768700/work/sage-8.1/src/sage/ext -Ibuild/cythonized -I/feedstock_root/build_artefacts/sagelib_1525107768700/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include/python2.7 -c build/cythonized/sage/libs/linbox/linbox_flint_interface.cpp -o build/temp.linux-x86_64-2.7/build/cythonized/sage/libs/linbox/linbox_flint_interface.o -fno-strict-aliasing -DCYTHON_CLINE_IN_TRACEBACK=1 -fno-tree-copyrename -O2 -Wall -g -DNDEBUG -U_LB_DEBUG -DDISABLE_COMMENTATOR -DFFLAS_COMPILED -DFFPACK_COMPILED -fabi-version=6 -I/feedstock_root/build_artefacts/sagelib_1525107768700/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include/linbox -I/feedstock_root/build_artefacts/sagelib_1525107768700/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include -std=gnu++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from /feedstock_root/build_artefacts/sagelib_1525107768700/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include/linbox/field/archetype.h:49:0,
                 from /feedstock_root/build_artefacts/sagelib_1525107768700/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include/linbox/vector/vector-traits.h:57,
                 from /feedstock_root/build_artefacts/sagelib_1525107768700/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include/linbox/matrix/dense-matrix.h:37,
                 from build/cythonized/sage/libs/linbox/linbox_flint_interface.cpp:692:
/feedstock_root/build_artefacts/sagelib_1525107768700/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include/linbox/util/debug.h:332:44: fatal error: fflas-ffpack/utils/print-utils.h: No such file or directory
 #include <fflas-ffpack/utils/print-utils.h>
                                            ^
compilation terminated.
error: command 'gcc' failed with exit status 1
```

**Comment by saraedum** [comment]
The header `print-utils.h` was removed in a741d5c5bf3e0e251e792644935e6f9105b4ba83 which was first released in fflas-ffpack 2.3.0.

**Comment by saraedum** [comment]
Hey, one file progress…
```
[152/468] creating build/temp.linux-x86_64-2.7/build/cythonized/sage/libs/lcalc
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -w -m64 -I/feedstock_root/build_artefacts/sagelib_1525787070310/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include -fPIC -Isage/libs/lcalc -I/feedstock_root/build_artefacts/sagelib_1525787070310/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python2.7/site-packages/cypari2 -Isage/cpython -Isage/libs/ntl -I/feedstock_root/build_artefacts/sagelib_1525787070310/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python2.7/site-packages/cysignals -I/feedstock_root/build_artefacts/sagelib_1525787070310/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include -I/feedstock_root/build_artefacts/sagelib_1525787070310/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include/python2.7 -I/feedstock_root/build_artefacts/sagelib_1525787070310/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python2.7/site-packages/numpy/core/include -I/feedstock_root/build_artefacts/sagelib_1525787070310/work/sage-8.1/src -I/feedstock_root/build_artefacts/sagelib_1525787070310/work/sage-8.1/src/sage/ext -Ibuild/cythonized -I/feedstock_root/build_artefacts/sagelib_1525787070310/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include/python2.7 -c build/cythonized/sage/libs/lcalc/lcalc_Lfunction.cpp -o build/temp.linux-x86_64-2.7/build/cythonized/sage/libs/lcalc/lcalc_Lfunction.o -fno-strict-aliasing -DCYTHON_CLINE_IN_TRACEBACK=1 -fno-tree-copyrename -std=gnu++98 -O3 -ffast-math
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from /feedstock_root/build_artefacts/sagelib_1525787070310/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include/linbox/ring/ntl.h:41:0,
                 from /feedstock_root/build_artefacts/sagelib_1525787070310/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include/linbox/ring/givaro-polynomial.h:99,
                 from build/cythonized/sage/libs/linbox/linbox_flint_interface.cpp:699:
/feedstock_root/build_artefacts/sagelib_1525787070310/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include/linbox/ring/ntl/ntl-zz_px.h:101:25: error: cannot declare parameter ‘cf’ to be of abstract type ‘LinBox::NTL_ZZ_p’
   NTL_ZZ_pX( CoeffField cf ) :
                         ^
```

**Comment by saraedum** [comment]
This is also #27.

**Comment by isuruf** [comment]
Can you rebase on master?

**Pull request merged**
