### PR TITLE
Build for Python3

### LINKED ISSUE #23: Build for Python3
Sage 8.2 should build with Python3. Let's give it a try…

### PR DESCRIPTION
**Pull request by saraedum**
fixes #23

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
Hm…that's weird for a python 3.6 build:
```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - cysignals=1.7 -> python=3.5 -> sqlite=3.9
  - python=3.6
```

**Comment by saraedum** [comment]
So, `sqlite=3.9` and `python=3.6` don't go together. But where does `sqlite=3.9` come from…

**Comment by isuruf** [comment]
https://travis-ci.org/conda-forge/cysignals-feedstock/jobs/370019083 was failing. Restarted it

**Comment by isuruf** [comment]
Looks like python 3.5 is not supported. Can you skip python=3.5?

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
@isuruf: Looks good to me. Do you want to add anything?

**Pull request merged**
