### PR TITLE
Rebuild for Arb 2.17 pin from conda-forge-pinnings

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
There's no need to rebuild sage as it only has arb in the run requirements.

**Comment by isuruf** [comment]
Need a rerender for the pinning to work.

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
> Need a rerender for the pinning to work.

Ok. On another feedstock the rerender did not do anything. It just picked up 2.17 for all the builds, so the run_exports sets it to the correct version. I guess it was too early and the rerender failed therefore. Anyway, if it happens to pick up 2.17 it's essentially fine also, right?

**Comment by saraedum** [comment]
@isuruf do you want to have a look at the conda-forge-webservice crash? Or should I ping core?

**Comment by saraedum** [comment]
On another feedstock, it just worked. Let's try again.

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Pull request merged**
